[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "qemu-system-x86_64 -kernel target/x86_64-unknown-none/debug/woodix -vga std -monitor stdio -nographic -debugcon file:debug.log -global isa-debugcon.iobase=0xe9 -d int,guest_errors -no-reboot"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-static",
    "-C", "link-arg=-n",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000"
]